// import './creational/factory/factory-concepts'
// import './creational/factory/client'
// import './creational/abstract-factory/abstract-factory-concept'
// import './creational/abstract-factory/client'
// import './creational/builder/builder-concept'
// import './creational/builder/client'
// import './creational/prototype/prototype-concept'
// import './creational/prototype/client'
// import './creational/singleton/singleton-concept'
// import './creational/singleton/client'

// import './structural/decorator/decorator-concept'
// import './structural/decorator/client'
import './structural/adapter/adapter-concept'
import './structural/adapter/client'